apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: etcd
  namespace: openshift-operators 
spec:
#  channel: singlenamespace-alpha
  channel: clusterwide-alpha
#  channel: alpha
  installPlanApproval: Automatic
  name: etcd
  source: community-operators 
  sourceNamespace: openshift-marketplace 
#  startingCSV: 0.9.4-clusterwide
