apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- namespace.yaml   # not needed as the openshift-operators namespace already exists
#- etcd-operatorgroup.yaml   # not necessary as an operator group already exists for the openshift-operators namespace
- etcd-operator.yaml
#- etcd-cluster.yaml
