---
# Source: regional-extension-server-common/templates/deployment_etcd.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rias-etcd
  namespace: rias
  labels:
    app:  rias-etcd
spec:
  selector:
    matchLabels:
      app: rias-etcd
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  rias-etcd
    spec:
      containers:
      - name:  rias-etcd
        image:  bitnami/etcd:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        ports:
        - containerPort:  2379
          name:  etcd
        - containerPort:  2380
          name:  etcd-2
        volumeMounts:
        - name: etcd-data
          mountPath: /data
# BEGIN TEST
#        command:
#          - /bin/sh
#          - -c
#          - |
#            PEERS="etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
#            exec etcd --name ${HOSTNAME} \
#              --listen-peer-urls http://0.0.0.0:2380 \
#              --listen-client-urls http://0.0.0.0:2379 \
#              --advertise-client-urls http://${HOSTNAME}.etcd:2379 \
#              --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
#              --initial-cluster-token etcd-cluster-1 \
#              --initial-cluster ${PEERS} \
#              --initial-cluster-state new \
#              --data-dir /data/default.etcd
# END TEST
      volumes:
        - name: etcd-data

          persistentVolumeClaim:
            claimName: pvc-volume

      restartPolicy: Always
