---
# Source: regional-extension-server-common/templates/deployment_etcd.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rias-etcd
  namespace: rias
  labels:
    app:  rias-etcd
spec:
  selector:
    matchLabels:
      app: rias-etcd
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  rias-etcd
    spec:
      containers:
      - name:  rias-etcd
        image:  bitnami/etcd:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        ports:
        - containerPort:  2379
          name:  etcd
        - containerPort:  2380
          name:  etcd-2
        volumeMounts:
        - name: etcd-data
          mountPath: /data
      volumes:
        - name: etcd-data

          persistentVolumeClaim:
            claimName: pvc-volume

      restartPolicy: Always
