---
# Source: regional-extension-server-common/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rias
  labels:
    argocd.argoproj.io/managed-by: argocd
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
    name: rias
