---
# Source: regional-extension-server-common/templates/rias_etcd_hostPath_pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
  namespace: rias
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
