# this loadbalancer service is only being created temporarily for testing purposes
apiVersion: v1
kind: Service
metadata:
  name: etcd-client-loadbalancer
  namespace: rias
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    etcd_cluster: etcd
  type: LoadBalancer
