---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rias-etcd:etcd-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  verbs:
  - "*"
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - persistentvolumes
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - etcd-client-tls
  - etcd-peer-tls
  - etcd-server-tls
  verbs:
  - get
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rias-etcd:etcd-operator-crt-cluster
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - etcd-client-tls-cluster
  - etcd-peer-tls-cluster
  - etcd-server-tls-cluster
  verbs:
  - get
  - update
  - delete
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rias-etcd:etcd-operator-crt-cluster-create
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create