apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: etcd-peer-ext-sec
  labels:
    kustomizeKey: etcd-peer-secrets
spec:
  data:
    - remoteRef:
        property: 'certificate'
        key: tnt-9e4ba32c-2638-4791-aef9-ce4d979d584f-roks/private_cert/sre-test-virt-4_9e4ba32c-2638-4791-aef9-ce4d979d584f_etcd_peer
        metadataPolicy: None
      secretKey: peer.crt
    - remoteRef:
        property: 'private_key'
        key: tnt-9e4ba32c-2638-4791-aef9-ce4d979d584f-roks/private_cert/sre-test-virt-4_9e4ba32c-2638-4791-aef9-ce4d979d584f_etcd_peer
        metadataPolicy: None
      secretKey: peer.key
    - remoteRef:
        property: 'certificate'
        key: default/imported_cert/sdsaas_eu-es_ca_chain
        metadataPolicy: None
      secretKey: peer-ca.crt
  secretStoreRef:
    kind: SecretStore
    name: sm-secret-store
  target:
    name: etcd-peer-tls