apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: etcd-server-ext-sec
  labels:
    kustomizeKey: etcd-server-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  data:
    - remoteRef:
        property: 'certificate'
        key: tnt-9e4ba32c-2638-4791-aef9-ce4d979d584f-roks/private_cert/sre-test-virt-4_9e4ba32c-2638-4791-aef9-ce4d979d584f_etcd_server
        metadataPolicy: None
      secretKey: server.crt
    - remoteRef:
        property: 'private_key'
        key: tnt-9e4ba32c-2638-4791-aef9-ce4d979d584f-roks/private_cert/sre-test-virt-4_9e4ba32c-2638-4791-aef9-ce4d979d584f_etcd_server
        metadataPolicy: None
      secretKey: server.key
    - remoteRef:
        property: 'certificate'
        key: default/imported_cert/sdsaas_eu-es_ca_chain
        metadataPolicy: None
      secretKey: server-ca.crt
  secretStoreRef:
    kind: SecretStore
    name: sm-secret-store
  target:
    name: etcd-server-tls