---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-secret-reader
  namespace: rias-etcd
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
  