---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: rias-etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-secret-reader
subjects:
- kind: ServiceAccount
  name: etcd-operator
