---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-operator
  namespace: rias-etcd
  labels:
    app: etcd-operator
imagePullSecrets:
- name: sdsaas-repo-pull-secret
#    release: {{ release_version }}