---
# Source: regional-extension-server-common/templates/etcd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rias-etcd
  namespace: rias
spec:
  selector:
    app: rias-etcd
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: etcd
    protocol: TCP
    port: 2379
    targetPort: 2379

  - name: etcd-2
    protocol: TCP
    port: 2380
    targetPort: 2380
